name: kaggle-disaster-tweets-env

channels:
  - pytorch
  - nvidia
  - defaults

dependencies:
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - pytorch
  - torchvision
  - pytorch-cuda
  - nltk